"""Posts update field

Revision ID: ee88b410e6b6
Revises: 111fb8e47d90
Create Date: 2024-10-26 23:55:31.983526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee88b410e6b6'
down_revision: Union[str, None] = '111fb8e47d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('last_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'last_modified')
    # ### end Alembic commands ###
