"""Posts remove title

Revision ID: faff330511d0
Revises: 86639eb695c0
Create Date: 2024-10-28 20:48:03.967933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faff330511d0'
down_revision: Union[str, None] = '86639eb695c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.drop_index('ix_posts_title', table_name='posts')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.create_index('ix_posts_title', 'posts', ['title'], unique=False)
    op.drop_column('posts', 'is_blocked')
    # ### end Alembic commands ###
